create table USERS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR (50) NOT NULL,
    EMAIL VARCHAR (50) NOT NULL,
    PASSWORD VARCHAR (30) NOT NULL,
    AVATAR BLOB NOT NULL,
    ROOT_FOLDER_ID INT NULL,
    PRIMARY KEY (ID)
);

create table FOLDERS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR (50) NOT NULL,
    CREATOR_ID INT NOT NULL,
    PARENT_FOLDER_ID INT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CREATOR_ID) REFERENCES USERS(ID)
);

create table DOCUMENTS (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR (50) NOT NULL,
    FILE_BLOB BLOB NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CREATOR_ID INT NOT NULL,
    TRASH BOOLEAN NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CREATOR_ID) REFERENCES USERS(ID)
);

create table FOLDER_FOLDERS (
    FOLDER_ID INT NOT NULL,
    CHILD_FOLDER_ID INT NOT NULL,
    PRIMARY KEY (FOLDER_ID, CHILD_FOLDER_ID),
    CONSTRAINT CONSTR_FOLDER_PARENT_FK
        FOREIGN KEY (FOLDER_ID) REFERENCES FOLDERS(ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CONSTR_FOLDER_CHILD_FK
        FOREIGN KEY (CHILD_FOLDER_ID) REFERENCES FOLDERS(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

create table FOLDER_DOCUMENTS (
    FOLDER_ID INT NOT NULL,
    DOCUMENT_ID INT NOT NULL,
    PRIMARY KEY (FOLDER_ID, DOCUMENT_ID),
    CONSTRAINT CONSTR_FOLDER_CONTAINER_FK
        FOREIGN KEY (FOLDER_ID) REFERENCES FOLDERS(ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CONSTR_DOCUMENT_FOLDER_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

create table DOCUMENT_EDITORS (
    USER_ID INT NOT NULL,
    DOCUMENT_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, DOCUMENT_ID),
    CONSTRAINT CONSTR_DOCUMENT_EDITOR_FK
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CONSTR_DOCUMENT_TO_EDIT_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

create table DOCUMENT_VIEWERS (
    USER_ID INT NOT NULL,
    DOCUMENT_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, DOCUMENT_ID),
    CONSTRAINT CONSTR_DOCUMENT_VIEWER_FK
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CONSTR_DOCUMENT_TO_VIEW_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE USERS
  ADD CONSTRAINT ROOT_FOLDER_FK FOREIGN KEY (ROOT_FOLDER_ID) 
  REFERENCES FOLDERS(id);

ALTER TABLE FOLDERS
  ADD CONSTRAINT PARENT_FOLDER_FK FOREIGN KEY (PARENT_FOLDER_ID) 
  REFERENCES FOLDERS(id) ON DELETE SET NULL ON UPDATE CASCADE;
